[tool.pyright]
include = ["src", "tests", "main.py"]
exclude = ["**/node_modules", "**/__pycache__", "**/site-packages", ".venv", "venv"]
# Nuclear option for RAM:
typeCheckingMode = "off"
reportMissingImports = false
reportMissingTypeStubs = false
